#!/bin/bash
# This script uses the metric system (1000 bytes to a KB etc) to measure size

# Scheme Chunk
NumbersScheme=('0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12')        # An array meant to help increment with for loops
Scheme=('Name' 'Rack position' 'Brand' 'Serial number' 'Size' 'Model' 'Revolutions per minute' 'Data interface' 'Power draw' 'Purpose' 'Format' 'Scheme' 'Debug port')

# Hard drive data chunk
HardDrive0=('Hard Drive 0' '' 'Western Digital' '' '' '' '' '' '' '' '' '' '')
HardDrive1=('Hard Drive 1' '' 'Toshiba' '' '' '' '' '' '' '' '' '' '')
HardDrive2=('Hard Drive 2' '' 'Western Digital' '' '' '' '' '' '' '' '' '' '')
HardDrive3=('Hard Drive 3' '' 'Western Digital' '' '' '' '' '' '' '' '' '' '')
HardDrive4=('Hard Drive 4' '' 'Western Digital' '' '' '' '' '' '' '' '' '' '')
HardDrive5=('Hard Drive 5' '' 'Western Digital' '' '' '' '' '' '' '' '' '' '')
HardDrive6=('Hard Drive 6' '' 'Western Digital' '' '' '' '' '' '' '' '' '' '')

# Master list chunk
NumberHardDrives=('0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12')       # The number of hard draves in the master array for 'for' loops
HardDrivesMaster=(${Scheme[@]} ${HardDrive0[@]} ${HardDrive1[@]} ${HardDrive2[@]} ${HardDrive3[@]} ${HardDrive4[@]} ${HardDrive5[@]} ${HardDrive6[@]})  # Master lists of all hard drives

# Excecutable chunk
for element in "${NumbersScheme[@]}"    #  Loops for every element in Scheme
do
        echo "${Scheme[element]}: ${HardDrive0[element]}"       # Prints the scheme and the coded hard drive's attributes that match
done
