#!/bin/bash
# Written by Willow Leahy
# This is my first script
# It has been revised to allow better functionality
# This script is a ssh command with default credential preloaded to make logging in faster. 
# Original script: 'ssh anonymousna@192.268.0.239'


# Default Credentials and variables
# Will be used if no flags are given
TARGETHOSTNAME=""
IP=""
USER=""
HOSTNAMEFLAG=0
IPFLAG=0
USERFLAG=0


# Flag(s) chunk
while [[ "$#" -gt 0 ]]; do
	if [[ "$#" -gt 1 ]]; then	# Warning that only 1 flag can be used at a time
		echo "Multiple flags have not been implemented. The following will not be proccessed: $2 $3 $4 $5 $6 $7 $8 $9"
	fi
	case "$1" in			# Checks the value of $1 against the below options
		-a)			# Allows custom Hostname, IP, and User 
			HOSTNAMEFLAG=1
			IPFLAG=1
			USERFLAG=1
			;;
		-h)
			HOSTNAMEFLAG=1	# User will be promted for a custom Hostname
			;;
		-i)
			IPFLAG=1	# User will be promted for a custom IP
			;;
		-u)			# User will be promted for a custom user
			USERFLAG=1
			;;
		*)			# The astrisk is a wildcard and will catch all inputs that are not listed above
			echo "Unknown flag: $1"; exit 1
	esac
done


# User input chunk
# Propts the user based on the flags
if [[ $HOSTNAMEFLAG == 1 ]]; then
	echo "What is the target's hostname?"
	read TARGETHOSTNAME	# Gets a user defined value for $HOSTNAME
elif [ "$IPFLAG" == 1 ]; then
	echo "What is the IP adress for $HOSTNAME?" 
	read IP			# Gets a user defined value for $IP
elif [ "$USERFLAG" == 1 ]; then
	echo "what user would you like to log in with?"
	read USER		# Gets a user defined value for $USER
fi


# Execution chunk
# ssh $HOSTNAME@$IP	# Initiates connection
# echo $USER	# Inputs username


echo "$TARGETHOSTNAME, $IP, $USER"	# Only used for testing functionality

exit 0	# Exits the script with a success status
