#!/bin/bash
# A script that allows profiles to be loaded for faster and secure remote management with ssh
# 'server-ssh' isn't super portable so if needed replace - with _

# Project steps:
#	Custom user
#		Input validation (current)
#		Error handling
#	Custom IPv4 only for now
#		Input validation
#		Error handling
#	List profiles
#	Load profiles
#		Basic Functionality
#		Input validation
#		Error handling
#	Save profiles
#		Basic Functionality
#		Only allow IPv4 adress
#		Input validation
#		Error handling
#	Allow options for IPv4 and v6
#		Core ssh command where the default profile contains a IPv6 address
#		Enable custom IPv6 entering
#       SFTP mode

# Default settings
USER=user
IP=xxx.xxx.xxx.xxx
EXECUTE=true
#MODE=ssh

# Loaded server profiles
HOSTNAME1="hostname"
IP1=xxx.xxx.xxx.xxx
USER1="user"

HOSTNAME2="hostname"
IP2=xxx.xxx.xxx.xxx
USER2="user"

HOSTNAME3="hostname"
IP3=xxx.xxx.xxx.xxx
USER3="user"

while getopts ":hrvuipsl" opt; do
	case $opt in
		h)
			echo "usage: server-ssh [-h] [-r] [-v] [-u user] [-i IP] [-p profile]
                  [-s hostname user IP] [-l]"
			echo "       -h      Displays this help message"
			echo "       -r      Logs in with root user instead of default user"
			echo "       -v      Enables verbose outputs"
			echo "       -u      Custom user can be entered."
			#echo "       -i      Custom IP can be entered."
			#echo "       -p      Loads saved profiles"
			#echo "       -s	     Creates and saves a new server profile"
			#echo "       -l      List all saved profiles"
			echo "default: $USER@$IP"
			echo "purpose: Establishes a ssh connection with a remote server. Can also load saved profiles."
			EXECUTE=false
			;;
		r)
			USER=root
			;;	
		v)
			VERBOSE=true	# Currently doesn't actually do anything (find out if this option needs to be here) (could just print the profile being used before the ssh command executes)
			;;
		u)
			echo -n "Enter username: " read USER
			# Include input validation
			# Rules:
			#	- Must be one string no white spaces
			#	- 32 char max leagnth
			#	- No capital letters
			#	- No periods
			#	- Don't end in a dash
			#	- No colons
                        # Include error handling
			;;
		i)
			#echo -n "Enter IPv4: " read IP
			# Include input validation
			# Rules:
			#	In IPv4 mode:
			#		- [0-255].[0-255].[0-255].[0-255]
			#		- Limit each section to a max number of "255".
			#		- Allow siplification so 000.000.000.000 can be entered as 0.0.0.0
			#	In IPv6 mode:
			#		- 
			# Include error handling
			;;
		p)
			# Loads saved profiles
			# These profiles should be moved to an external file but for now they will be hard coded
			# Include input validation
                        # Include error handling
			;;
		s)
			# Will save the user and IP entered
			# Needs a bit of logic so that the new profile will keep the properties of the one loaded
			#	if all field aren't filled out (hostname, IPv4 or IPv6, user)
			# Include input validation
                        # Include error handling
			;;
		l)
			# List all saved profiles
			;;
		*)
			echo "Unkown option: $OPTARG"
			# Padding to make the help line stand out
			echo ""
			echo "To display command help use -h flag"
			echo ""
			EXECUTE=false
			;;
	esac
done

if [ "$EXECUTE" = "true" ]; then
	ssh $USER@$IP
fi
