#!/bin/bash
# A script that allows profiles to be loaded for faster and secure remote management
# 'server-ssh' isn't super portable so if needed replace - with _

# Saved server profiles
hostname_1="hostname"
user_1="user"
ip_1="xxx.xxx.xxx.xxx"
port_1="22"
key_authentication1="true"

hostname_2="hostname"
user_2="user"
ip_2="xxx.xxx.xxx.xxx"
port_2="22"
key_authentication2="true"

hostname_3="hostname"
user_3="user"
ip_3="xxx.xxx.xxx.xxx"
port_3="22"
key_authentication3="true"

# Default settings
user=user_1
ip=ip_1
port=port_1
key_authentication=key_authentication1
execute="true"	# Determines if a connectiopn will be attempted (used mostly for error handling)
mode="ssh"	# The sucure connection being attempted
ip_mode="IPv4"
verbose="false"

while getopts ":hrvuipsl" opt; do
	case $opt in
		h)
			echo "usage: server-ssh [-h] [-r] [-v] [-u user] [-i IP] [-p profile]
                  [-s hostname user IP] [-l]"
			echo "       -h      Displays this help message"
			echo "       -r      Logs in with root user instead of default user"
			echo "       -v      Enables verbose outputs"
			echo "       -u      Custom user can be entered."
			#echo "       -i      Custom IP can be entered."
			#echo "       -p      Loads saved profiles"
			#echo "       -s	     Creates and saves a new server profile"
			#echo "       -l      List all saved profiles"
			echo "default: $user@$ip"
			echo "purpose: Establishes a ssh connection with a remote server. Can also load saved profiles."
			execute=false
			;;
		r)
			user=root
			;;	
		v)
			verbose=true	# Currently doesn't actually do anything (find out if this option needs to be here) (could just print the profile being used before the ssh command executes)
			;;
		u)
			echo -n "Enter username: " read user
			;;
		i)
			echo -n "Enter IPv4 address: " read ip
			;;
		p)
			# Loads saved profiles
			# These profiles should be moved to an external file but for now they will be hard coded
			# Include input validation
                        # Include error handling
			#	Make a single function and just have it call when an error state has occored
			;;
		s)
			# Will save the user and IP entered
			# Needs a bit of logic so that the new profile will keep the properties of the one loaded
			#	if all field aren't filled out (hostname, IPv4 or IPv6, user)
			# Include input validation
                        # Include error handling
			#	Make a single function and just have it call when an error state has occored
			;;
		l)
			# List all saved profiles
			;;
		*)
			echo "Unkown option: $OPTARG"
			# Padding to make the help line stand out
			echo ""
			echo "To display command help use -h flag"
			echo ""
			execute=false
			;;
	esac
done

if [ "$execute" = "true" ]; then
	$mode $user@$ip
fi
